In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam

# ------------------- 데이터 로딩 -------------------

df = pd.read_csv("https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/abalone.csv")
df

,id,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...,...
4172,4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [3]:
# ------------------- 데이터 전처리 -------------------

# 성별(Sex) 컬럼 Label Encoding
encoder = LabelEncoder()
df['Sex'] = encoder.fit_transform(df['Sex'])

print("\nEncoded DataFrame:\n", df.head())

Encoded DataFrame:
    id  Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  \
0   0    2   0.455     0.365   0.095        0.5140          0.2245
1   1    2   0.350     0.265   0.090        0.2255          0.0995
2   2    0   0.530     0.420   0.135        0.6770          0.2565
3   3    2   0.440     0.365   0.125        0.5160          0.2155
4   4    1   0.330     0.255   0.080        0.2050          0.0895

   Viscera_weight  Shell_weight  Rings
0          0.1010         0.150     15
1          0.0485         0.070      7
2          0.1415         0.210      9
3          0.1140         0.155     10
4          0.0395         0.055      7

In [5]:
# ------------------- Feature / Target 분리 -------------------

X = df.drop('Rings', axis=1).values  # 입력 변수 (길이, 무게 등)
y = df['Rings'].values               # 타겟 변수 (나이 예측)

print("\nFeature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (4177, 9)
Target shape: (4177,)

In [7]:

# ------------------- 데이터 분할 -------------------

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print("\nTrain/Test size:")
print("X_train:", X_train.shape, "X_test:", X_test.shape)
print("y_train:", y_train.shape, "y_test:", y_test.shape)

# ------------------- 데이터 스케일링 -------------------

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Train/Test size:
X_train: (3341, 9) X_test: (836, 9)
y_train: (3341,) y_test: (836,)